### ISSUE TITLE
Build awsme for the Lambda environment

### ISSUE THREAD

**Issue by joseph-wortmann** [peterdemin/awsme#3]
* Amazon Web Services Cloud Watch Metrics library version: 0.2.5
* Python version: 3.6, 3.7
* Operating System: AWS Lambda

### Description

The awsme library has as an install_includes `boto3`. This is perfect and appropriate for most applications of the library, but it does not work well for AWS Lambda applications of the library.

The reason is as follows: boto3 and the AWS API changes pretty rapidly, and AWS updates the Lambda runtime in sync with those changes. Best practices for Lambda functions are to NOT include boto3 in the lambda function package to prevent weird incompatibilities between the AWS API and older versions of boto3. Also, it prevents MAJOR package bloat.

What I've done in the past is fork project that have boto3, remove boto3 as a dependency, and upload the new build to pypi as lambda-<project name>. However, this is sub-optimal, obviously, as it only loosely tracks the primary project.

Could we alter the build to both produce `awsme` for standard applications and in the same run produce `lambda-awsme` for Lambda applications?

**Comment by peterdemin** [comment]
Interesting. I think we can make a major release with `boto3` in [extras_require](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).
So that `pip install awsme` will not install boto3, but `pip install awsme[boto3]` will.
What do you think? Can you PR that?
Also, I noticed, that in the previous PR the requirements files intentions changed. Please run `tox -e upgrade3` to fix it.

**Comment by joseph-wortmann** [comment]
Yeah, I can PR that tonight, no problem! That is a great solution - I've learned something new.

**Comment by joseph-wortmann** [comment]
I'm running the tox stuff now. PR is available for you

**Comment by peterdemin** [comment]
But don't bumpversion inside the PR, it has to be done in the master branch so that TravisCI will make a release.

**Comment by joseph-wortmann** [comment]
Got it.

Also - need a bit of help on the `extras_require`. I've got `boto3` extracted from the standard requires, but I'm not sure how to get `tox` to install it so that it is available for the test runs. Any pointers are very welcome.

**Comment by peterdemin** [comment]
I didn't undertand the problem. Could you please open a PR so I can see what's wrong?

**Comment by joseph-wortmann** [comment]
Yep - on it.

**Comment by peterdemin** [comment]
Enjoy v1.0.0

**Comment by peterdemin** [comment]
Enjoy v1.0.0
