### ISSUE TITLE
Throughput benchmark

### ISSUE THREAD

**Issue by bfelbo** [peterdemin/awsme#90]
Hi, this library looks great 😄

I'm wondering if you have any benchmarking on how many metrics you can send to AWS per second? We send quite a few metrics so I'd love if our use case is supported with this metrics.

**Comment by peterdemin** [comment]
In my experience it’s more than what we could afford. 
I’m no longer in that project, so you are welcome to submit your benchmarking results to the Readme.

**Comment by bfelbo** [comment]
Okay, thanks. I'll take a stab at it.
